export const currency = [
  "Currency",
  "Afghan Afghani (AFN)",
  "Albanian Lek (ALL)",
  "Algerian Dinar (DZD)",
  "Angolan Kwanza (AOA)",
  "Argentine Peso (ARS)",
  "Armenian Dram (AMD)",
  "Aruban Florin (AWG)",
  "Australian Dollar (AUD)",
  "Azerbaijani Manat (AZN)",
  "Bahamian Dollar (BSD)",
  "Bahraini Dinar (BHD)",
  "Bangladeshi Taka (BDT)",
  "Barbadian Dollar (BBD)",
  "Belarusian Ruble (BYN)",
  "Belarusian Ruble (BYR)",
  "Belize Dollar (BZD)",
  "Bermudian Dollar (BMD)",
  "Bhutanese Ngultrum (BTN)",
  "Bolivian Boliviano (BOB)",
  "Bosnia and Herzegovina Convertible Mark (BAM)",
  "Botswana Pula (BWP)",
  "Brazilian Real (BRL)",
  "British Penny (GBX)",
  "British Pound (GBP)",
  "Brunei Dollar (BND)",
  "Bulgarian Lev (BGN)",
  "Burundian Franc (BIF)",
  "Cambodian Riel (KHR)",
  "Canadian Dollar (CAD)",
  "Cape Verdean Escudo (CVE)",
  "Cayman Islands Dollar (KYD)",
  "Central African Cfa Franc (XAF)",
  "Cfp Franc (XPF)",
  "Chilean Peso (CLP)",
  "Chinese Renminbi Yuan (CNY)",
  "Chinese Renminbi Yuan Offshore (CNH)",
  "Colombian Peso (COP)",
  "Comorian Franc (KMF)",
  "Congolese Franc (CDF)",
  "Costa Rican Colón (CRC)",
  "Croatian Kuna (HRK)",
  "Cuban Convertible Peso (CUC)",
  "Czech Koruna (CZK)",
  "Danish Krone (DKK)",
  "Djiboutian Franc (DJF)",
  "Dominican Peso (DOP)",
  "East Caribbean Dollar (XCD)",
  "Egyptian Pound (EGP)",
  "Estonian Kroon (EEK)",
  "Ethiopian Birr (ETB)",
  "Euro (EUR)",
  "Falkland Pound (FKP)",
  "Fijian Dollar (FJD)",
  "Gambian Dalasi (GMD)",
  "Georgian Lari (GEL)",
  "Ghanaian Cedi (GHS)",
  "Gibraltar Pound (GIP)",
  "Gold (Troy Ounce) (XAU)",
  "Guatemalan Quetzal (GTQ)",
  "Guernsey Pound (GGP)",
  "Guinean Franc (GNF)",
  "Guyanese Dollar (GYD)",
  "Haitian Gourde (HTG)",
  "Honduran Lempira (HNL)",
  "Hong Kong Dollar (HKD)",
  "Hungarian Forint (HUF)",
  "Icelandic Króna (ISK)",
  "Indian Rupee (INR)",
  "Indonesian Rupiah (IDR)",
  "Iraqi Dinar (IQD)",
  "Isle of Man Pound (IMP)",
  "Israeli New Sheqel (ILS)",
  "Jamaican Dollar (JMD)",
  "Japanese Yen (JPY)",
  "Jersey Pound (JEP)",
  "Jordanian Dinar (JOD)",
  "Kazakhstani Tenge (KZT)",
  "Kenyan Shilling (KES)",
  "Kuwaiti Dinar (KWD)",
  "Kyrgyzstani Som (KGS)",
  "Lao Kip (LAK)",
  "Latvian Lats (LVL)",
  "Lebanese Pound (LBP)",
  "Lesotho Loti (LSL)",
  "Liberian Dollar (LRD)",
  "Libyan Dinar (LYD)",
  "Lithuanian Litas (LTL)",
  "Macanese Pataca (MOP)",
  "Macedonian Denar (MKD)",
  "Malagasy Ariary (MGA)",
  "Malawian Kwacha (MWK)",
  "Malaysian Ringgit (MYR)",
  "Maldivian Rufiyaa (MVR)",
  "Mauritanian Ouguiya (MRO)",
  "Mauritian Rupee (MUR)",
  "Mexican Peso (MXN)",
  "Moldovan Leu (MDL)",
  "Mongolian Tögrög (MNT)",
  "Moroccan Dirham (MAD)",
  "Mozambican Metical (MZN)",
  "Myanmar Kyat (MMK)",
  "Namibian Dollar (NAD)",
  "Nepalese Rupee (NPR)",
  "Netherlands Antillean Gulden (ANG)",
  "New Taiwan Dollar (TWD)",
  "New Zealand Dollar (NZD)",
  "Nicaraguan Córdoba (NIO)",
  "Nigerian Naira (NGN)",
  "Norwegian Krone (NOK)",
  "Omani Rial (OMR)",
  "Pakistani Rupee (PKR)",
  "Palladium (XPD)",
  "Panamanian Balboa (PAB)",
  "Papua New Guinean Kina (PGK)",
  "Paraguayan Guaraní (PYG)",
  "Peruvian Sol (PEN)",
  "Philippine Peso (PHP)",
  "Platinum (XPT)",
  "Polish Złoty (PLN)",
  "Qatari Riyal (QAR)",
  "Romanian Leu (RON)",
  "Russian Ruble (RUB)",
  "Rwandan Franc (RWF)",
  "Saint Helenian Pound (SHP)",
  "Salvadoran Colón (SVC)",
  "Samoan Tala (WST)",
  "Saudi Riyal (SAR)",
  "Serbian Dinar (RSD)",
  "Seychellois Rupee (SCR)",
  "Sierra Leonean Leone (SLL)",
  "Silver (Troy Ounce) (XAG)",
  "Singapore Dollar (SGD)",
  "Slovak Koruna (SKK)",
  "Solomon Islands Dollar (SBD)",
  "Somali Shilling (SOS)",
  "South African Rand (ZAR)",
  "South Korean Won (KRW)",
  "Sri Lankan Rupee (LKR)",
  "Sudanese Pound (SDG)",
  "Surinamese Dollar (SRD)",
  "Swazi Lilangeni (SZL)",
  "Swedish Krona (SEK)",
  "Swiss Franc (CHF)",
  "São Tomé and Príncipe Dobra (STD)",
  "Tajikistani Somoni (TJS)",
  "Tanzanian Shilling (TZS)",
  "Thai Baht (THB)",
  "Tongan Paʻanga (TOP)",
  "Trinidad and Tobago Dollar (TTD)",
  "Tunisian Dinar (TND)",
  "Turkish Lira (TRY)",
  "Turkmenistani Manat (TMM)",
  "Turkmenistani Manat (TMT)",
  "US Dollar (USD)",
  "Ugandan Shilling (UGX)",
  "Ukrainian Hryvnia (UAH)",
  "Unidad de Fomento (CLF)",
  "United Arab Emirates Dirham (AED)",
  "Uruguayan Peso (UYU)",
  "Uzbekistan Som (UZS)",
  "Vanuatu Vatu (VUV)",
  "Venezuelan Bolívar(VEF)",
  "Venezuelan Bolívar Soberano (VES)",
  "Vietnamese Đồng (VND)",
  "West African Cfa Franc (XOF)",
  "Yemeni Rial (YER)",
  "Zambian Kwacha (ZMK)",
  "Zambian Kwacha (ZMW)",
  "Zimbabwean Dollar (ZWD)",
];
